### ISSUE TITLE
no forwarding?

### ISSUE THREAD

**Issue by Zibri** [raonigabriel/web-terminal#1]
I started the docker container then ran ngrok.
I get:

ngrok does not support a dynamic, color terminal UI on solaris.
Access the web interface for connection and tunnel status.

Version                       2.3.40
Region                        Europe (eu)
Web Interface                 http://127.0.0.1:4040

but not the forwarding message...

**Comment by raonigabriel** [comment]
I wil try to repeoduce.
Can you provide the cmdline you used to start the container? And the cmdline to start ngrok?

**Comment by Zibri** [comment]
exactly as written in the README

**Comment by raonigabriel** [comment]
As for the "ngrok does not support a dynamic, color terminal UI on solaris", it seems to be a just **warning** caused on ngrok because it thinks ish is solaris, as we can see [here](https://www.gitmemory.com/issue/ish-app/ish/885/686189755).

That brings me to the question: are you using ish-app on an iOS device, is that so?
