### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by luizhenriquemm** [raonigabriel/web-terminal#4]
Is there any way to set any auth? I couldn't find any...

Thanks

**Comment by raonigabriel** [comment]
Yes, you have two options:

1) Use the internal "ttyd" --credential option. To do this , you will probably need to run the container with a custom "CMD"
See [here](https://github.com/tsl0922/ttyd#command-line-options) and [here](https://github.com/raonigabriel/web-terminal/blob/master/amd64/Dockerfile#L26) for more help. I think the easyest way is to create your derived image and add it to the CMD section.

2) Use "ngrok" basic-auth option. See [here](https://ngrok.com/docs/http/basic-auth/)
---

But to be honest... I am planning to update this project to remove the "ngrok" from it and just provide the "ttyd" biary. This is due a few reasons:
1) Ngrok has its own docker image that could be used alongside with ttyd (in a docker-compose file) in order to provide the tunnel.
2) There are a lot of other options instead of ngrok to provide tunneling, either free/paid and opensource like Cloudflare Tunnel, RatHole, Tailscale Funnel
3) Ngrok is not on the the main Alpine repository, thats why I never updated this project: it would require me to monitor every new release of them and update the Dockerfiles, one for each architecture coz each binary has its own download URL.
 
 That being said, I will probably release a "2.0.0" version of this with just ttyd in a couple days.
